### ISSUE TITLE
Support selecting text when running a command

### ISSUE THREAD

**Issue by joestringer** [cilium/microscope#33]
I ran `microscope --force-command "cilium endpoint list"`, and wanted to be able to select an endpoint ID so that I could copy it and run a command in another tab, but mouseclicks into the terminal produced weird output like this and did not allow me to select text:

```
/usr/src/microscope # -./3M@M@??1?2?2?3q9t9w9x9y9y9z9z9{9{9x:?:?:o8q8t8{9?9?9?9?9?9?9?9v"s"r"q"p"n"k"j"?%?%?%?$?#{"p"g"c"^"Z"X"
```

**Comment by joestringer** [comment]
Might be an issue with the shell in use, doesn't seem to only affect microscope when running the program, but rather the entire container image when run under k8s as per the readme.

**Comment by nebril** [comment]
Running on zsh and tmux, I am able to use mouse to select text, but I need to press shift (it should work with fn on OSX).

This seems to be the default behaviour of urwid (GUI library used by microscope).

This should be shown in the header text.

Please let me know if this works for you.

**Comment by nebril** [comment]
also https://github.com/urwid/urwid/wiki/FAQ#why-cant-i-select-text-in-an-urwid-program

Since we don't support any mouse navigation, I will fix this by disabling mouse handling.
