### ISSUE TITLE
Support vertical splits for panes

### ISSUE THREAD

**Issue by joestringer** [cilium/microscope#34]
Sometimes monitor provides quite wide output, or even when sending a command out to the nodes the output may be quite wide. In this case it would be nice if we can support splitting the microscope output into vertical splits instead of the default horizontal splits. Then it would be easier to read line-by-line output.

Alternative could be something similar to "zoom mode" from tmux, where you press a key (like `^z`) and it focuses only on one pane and "maximises" that view, then if you press it again it goes back to the main view.

**Comment by nebril** [comment]
@joestringer let me know if zoom mode introduced with latest patch is good enough.
