### ISSUE TITLE
Running microscope pod leaves host shell without cursor

### ISSUE THREAD

**Issue by joestringer** [cilium/microscope#45]
I ran the microscope pod like this:

```
kubectl run -i -n kube-system --tty microscope --image cilium/microscope --restart=Never
```

And after running, my shell's cursor disappeared.

Any ideas what's happening here?

**Comment by joestringer** [comment]
When I ran a command by using `--send-command`, and exited, the cursor returned.

**Comment by nebril** [comment]
Will check it out, thanks for the report.

**Comment by nebril** [comment]
@joestringer can you give me some more information on this? what shell are you using, how often does this happen? This seems more like kubectl issue, but I was unable to reproduce it by any means.

**Comment by joestringer** [comment]
I run bash inside tmux. I haven't used microscope for a while, so I'm not sure how often it happens.

**Comment by joestringer** [comment]
Haven't seen this in a while. We can always reopen if this issue is hit again.
