### ISSUE TITLE
Command in readme needs namespace

### ISSUE THREAD

**Issue by joestringer** [cilium/microscope#70]
I deployed the YAML for microscope using the instructions in the readme, and I could not connect using this command:

```
$ kubectl exec -it microscope sh
error: unable to upgrade connection: container not found ("microscope")
```

This is because the default YAML deployed microscope into the `kube-system` namespace. The above command needs updating in the README.

**Comment by raybejjani** [comment]
err, but isn't that the namespace the exec is in? `-n kube-system` ?

**Comment by joestringer** [comment]
@raybejjani woops, I copy-pasted the command from my terminal that worked, not the one from the readme.

**Comment by joestringer** [comment]
Doesn't seem to be the case any more.
